Bump rails from 8.1.2 to 8.1.3 (#93)
Bumps [rails](https://github.com/rails/rails) from 8.1.2 to 8.1.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">rails's
releases</a>.</em></p>
<blockquote>
<h2>8.1.3</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>JSONGemCoderEncoder</code> to correctly serialize custom
object hash keys.</p>
<p>When hash keys are custom objects whose <code>as_json</code> returns
a Hash,
the encoder now calls <code>to_s</code> on the original key object
instead of
on the <code>as_json</code> result.</p>
<p>Before:
hash = {CustomKey.new(123) =&gt; &quot;value&quot;}
hash.to_json  # =&gt; {&quot;{:id=&gt;123}&quot;:&quot;value&quot;}</p>
<p>After:
hash.to_json  # =&gt; {&quot;custom_123&quot;:&quot;value&quot;}</p>
<p><em>Dan Sharp</em></p>
</li>
<li>
<p>Fix inflections to better handle overlapping acronyms.</p>
<pre lang="ruby"><code>ActiveSupport::Inflector.inflections(:en) do
|inflect|
  inflect.acronym &quot;USD&quot;
  inflect.acronym &quot;USDC&quot;
end
<p>&quot;USDC&quot;.underscore # =&gt; &quot;usdc&quot;<br />
</code></pre></p>
<p><em>Said Kaldybaev</em></p>
</li>
<li>
<p>Silence Dalli 4.0+ warning when using
<code>ActiveSupport::Cache::MemCacheStore</code>.</p>
<p><em>zzak</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Fix Ruby 4.0 delegator warning when calling inspect on
attributes.</p>
<p><em>Hammad Khan</em></p>
</li>
<li>
<p>Fix <code>NoMethodError</code> when deserialising
<code>Type::Integer</code> objects marshalled under Rails 8.0.</p>
<p>The performance optimisation that replaced <code>@range</code> with
<code>@max</code>/<code>@min</code>
broke Marshal compatibility. Objects serialised under 8.0 (with
<code>@range</code>)
and deserialised under 8.1 (expecting
<code>@max</code>/<code>@min</code>) would crash with
<code>undefined method '&lt;=' for nil</code> because
<code>Marshal.load</code> restores instance
variables without calling <code>initialize</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/fa8f0812160665bff083a089d2bb2fc1817ea03e"><code>fa8f081</code></a>
Preparing for 8.1.3 release</li>
<li><a
href="https://github.com/rails/rails/commit/63cef3de3bd88d5973837ea268dc710e7dbf7b8e"><code>63cef3d</code></a>
Merge branch '8-1-sec' into 8-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/1db4b89687cc18311fc3f92623136705df24e671"><code>1db4b89</code></a>
Preparing for 8.1.2.1 release</li>
<li><a
href="https://github.com/rails/rails/commit/1c7d1cf0a1ab4142eb20ef30fe2062aad6f72e21"><code>1c7d1cf</code></a>
Update changelog</li>
<li><a
href="https://github.com/rails/rails/commit/e91694b1f0e176eb01bfcc480a008bffc70f7602"><code>e91694b</code></a>
Update CHANGELOG (8.1 only)</li>
<li><a
href="https://github.com/rails/rails/commit/6752711c8c31d79ba50d13af6a6698a3b85415e0"><code>6752711</code></a>
Fix XSS in debug exceptions copy-to-clipboard</li>
<li><a
href="https://github.com/rails/rails/commit/63f5ad83edaa0b976f82d46988d745426aa4a42d"><code>63f5ad8</code></a>
Skip blank attribute names in Action View tag helpers</li>
<li><a
href="https://github.com/rails/rails/commit/8c9676b803820110548cdb7523800db43bc6874c"><code>8c9676b</code></a>
Prevent glob injection in ActiveStorage DiskService#delete_prefixed</li>
<li><a
href="https://github.com/rails/rails/commit/9b06fbc0f504b8afe333f33d19548f3b85fbe655"><code>9b06fbc</code></a>
Prevent path traversal in ActiveStorage DiskService</li>
<li><a
href="https://github.com/rails/rails/commit/ec1a0e215efd27a3b3911aae6df978a80f456a49"><code>ec1a0e2</code></a>
Improve performance of NumberToDelimitedConverter</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v8.1.2...v8.1.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rails&package-manager=bundler&previous-version=8.1.2&new-version=8.1.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

> **Note**
> Automatic rebases have been disabled on this pull request as it has
been open for over 30 days.

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>